{% set version = "2.3" %}

package:
  name: teensy_loader_cli
  version: {{ version }}

source:
  url: https://github.com/PaulStoffregen/teensy_loader_cli/archive/refs/tags/{{ version }}.tar.gz
  sha256: d9c5357d7e8b99e9a9ae93f5e921c35a133a4a5d399f57eec10f3a606be5d89f
  patches:
    # https://github.com/PaulStoffregen/teensy_loader_cli/pull/52
    - osx_makefile_cleanup.patch
    # Specify soft reboot serial number
    # https://github.com/PaulStoffregen/teensy_loader_cli/pull/57
    - 57.patch
    # Fail on soft reboot failure
    # https://github.com/PaulStoffregen/teensy_loader_cli/pull/58
    - 58.patch
    # Windows HID location changed
    # https://github.com/PaulStoffregen/teensy_loader_cli/issues/51
    - 59.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}        # [unix]
    - {{ stdlib('c') }}          # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('m2w64_c') }}    # [win]
    - make                       # [unix]
  host:
    - libusb-compat              # [linux]

test:
  commands:
    # Command seems to return non-zero even though it lists things successfully
    - teensy_loader_cli --list-mcus | grep Supported         # [unix]
    - teensy_loader_cli --list-mcus | findstr Supported      # [win]

about:
  home: https://www.pjrc.com/teensy/loader_cli.html
  license: GPL-3.0-only
  license_family: GPL
  license_file: gpl3.txt
  summary: 'The Teensy Loader is available in a command line version for advanced users who want to automate programming'

extra:
  recipe-maintainers:
    - hmaarrfk
