# Technically not 2.1.1, but it is not version 2.1, so ...
# 2.1.1 had osx_makefile_cleanup + hid_location_windows patch
# 2.1.2 has 57 and 58 patch
# 2.1.3 has patch from https://github.com/PaulStoffregen/teensy_loader_cli/pull/66
#       as well as support for Teensy 4.1
{% set version = "2.1.2" %}

package:
  name: teensy_loader_cli
  version: {{ version }}

source:
  git_url: https://github.com/PaulStoffregen/teensy_loader_cli.git
  # Build off a recent master since 2019/11/09
  # upstream asked to create tags but no response.
  # https://github.com/PaulStoffregen/teensy_loader_cli/issues/13
  git_rev: 9dbbfa3b367b6c37e91e8a42dae3c6edfceccc4d
  # git_rev: master
  patches:
    # https://github.com/PaulStoffregen/teensy_loader_cli/pull/52
    - osx_makefile_cleanup.patch
    # Specify soft reboot serial number
    # https://github.com/PaulStoffregen/teensy_loader_cli/pull/57
    - 57.patch
    # Fail on soft reboot failure
    # https://github.com/PaulStoffregen/teensy_loader_cli/pull/58
    - 58.patch
    # Windows HID location changed
    # https://github.com/PaulStoffregen/teensy_loader_cli/issues/51
    - 59.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make      # [unix]
    - m2-make   # [win]
    - m2-patch  # [win]
  host:
    - libusb-compat  # [linux]
  run:
    - libusb-compat  # [linux]

test:
  commands:
    # Command seems to return non-zero even though it lists things successfully
    - teensy_loader_cli --list-mcus | grep Supported         # [unix]
    - teensy_loader_cli.exe --list-mcus | findstr Supported  # [win]

about:
  home: https://www.pjrc.com/teensy/loader_cli.html
  license: GPL-3.0-only
  license_family: GPL
  license_file: gpl3.txt
  summary: 'The Teensy Loader is available in a command line version for advanced users who want to automate programming'

extra:
  recipe-maintainers:
    - hmaarrfk
